FROM mongo

WORKDIR /etc/test

RUN apt update
RUN apt install -y nodejs npm
RUN npm install --global bunyan

COPY package.json .
COPY package-lock.json .
COPY build build
COPY node_modules node_modules
COPY revisions-mongodb revisions

# Copy and rename files to order their run order
COPY docker/mongodb/create-user.js /docker-entrypoint-initdb.d/000_create-user.js
COPY docker/mongodb/migrate.sh /docker-entrypoint-initdb.d/000_migrate.sh
