version: '3.8'
services:
  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo
    expose:
      - '27017'
    ports:
      - '27017:27017'
    command: --replSet mongodb-replica-set --config /etc/mongo/mongod.conf
    volumes:
      - './docker/mongodb/mongod.conf:/etc/mongo/mongod.conf:ro'
      - './docker/mongodb/setup-replica-set.js:/docker-entrypoint-initdb.d/setup-replica-set.js:ro'
