name: Build Artifact
on:
  push:
    branches: [master]
permissions:
  contents: read  # required for checkout action
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.1'
          cache: 'npm'
      - run: npm audit --audit-level moderate
      - run: npm install
      - run: npm test
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.1'
          cache: 'npm'
      - run: npm audit --audit-level moderate
      - run: npm install
      - run: npm lint
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./packages/cli
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.1'
          cache: 'npm'
      - run: npm audit --audit-level moderate
      - run: npm install
      - run: npm run build
      - name: Save Artifact CLI
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: db-revisions-artifact
          path: |
            build
            package.json
            package-lock.json
            LICENSE
          retention-days: 3
