name: Build Artifact
on:
  push:
    branches: [master]
permissions:
  contents: read  # required for checkout action
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.1'
          cache: 'npm'
      - name: build types package
        run: npm audit --audit-level low && npm install && npm run build
        working-directory: packages/types
      - name: build mongodb package
        run: npm audit --audit-level none && npm install && npm run build
        working-directory: packages/mongodb
      - name: build postresql package
        run: npm audit --audit-level none && npm install && npm run build
        working-directory: packages/postgresql
      - name: build cli package
        run: npm audit --audit-level none && npm install && npm run build
        working-directory: packages/cli
      - name: setup project development
        run: npm audit --audit-level none && npm install
      - run: npm run test
      - run: npm run lint
      - name: save artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: database-revisions-artifact
          path: |
            packages/types/build
            packages/types/package.json
            packages/types/package-lock.json

            packages/mongodb/build
            packages/mongodb/package.json
            packages/mongodb/package-lock.json

            packages/postgresql/build
            packages/postgresql/package.json
            packages/postgresql/package-lock.json

            packages/cli/build
            packages/cli/package.json
            packages/cli/package-lock.json
            packages/cli/LICENSE
          retention-days: 3
