name: Build Artifact
on:
  push:
    branches: [master]
permissions:
  contents: read  # required for checkout action
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18.1'
          cache: 'npm'
      - run: npm install && npm run build
        working-directory: packages/types
      - run: npm install && npm run build
        working-directory: packages/cli
      - run: npm install
      - run: npm run test
      - run: npm run lint
      - name: Save Artifact CLI
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: db-revisions-artifact
          path: |
            packages/cli/build
            packages/cli/package.json
            packages/cli/package-lock.json
            packages/cli/LICENSE
          retention-days: 3
